version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80" # Porta externa mapeada para a porta interna do container
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Porta externa mapeada para a porta interna do container
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
